GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJoZW5yeSIsImlhdCI6MTY3ODE4NjQwNSwiZXhwIjoxNjc4MTg2NzA1fQ.0wywAYflHxn9HA_DRMD3hKOVYSG9jW5IqnFoSswRxAA

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"henry"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"khoi"
}

###

POST http://localhost:5000/token
Content-Type: application/json

{
    "refreshToken": "eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJraG9pIiwiaWF0IjoxNjc4MTg2NDAxLCJleHAiOjE2NzgxOTAwMDF9.0urc4J9SOTDJeXwxqnBOPsqfwKOm_87VOssu_EoZcdY"
}

###
DELETE http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJraG9pIiwiaWF0IjoxNjc4MTg2NDU2LCJleHAiOjE2NzgxODY3NTZ9.9o2iZ_vrkjqK5kOJeamFynJCtHyMxqodPw09eNjZaxo